version: '3.8'

services:
  backend_atu_lake_api:
    container_name: backend_atu_lake_api
    build: .
    image: backend_atu_lake_api
    ports:
      - "3072:3072"
    volumes:
      - ./data:/opt/atu_lake_api/data
      - ./config.yml:/opt/atu_lake_api/config.yml
    restart: unless-stopped